CREATE DATABASE IF NOT EXISTS photo_app
DEFAULT CHARACTER SET utf8mb4 
COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS accounts(
    id INT AUTO_INCREMENT PRIMARY KEY,
    user VARCHAR(20) NOT NULL,
    pass VARCHAR(255) NOT NULL,
    email_address VARCHAR(255) NOT NULL,
    create_date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_user (user),
    UNIQUE KEY unique_email (email_address)
);

CREATE TABLE IF NOT EXISTS `groups`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    group_name VARCHAR(20) NOT NULL,
    account_id INT NOT NULL,
    create_date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (group_name),
    INDEX (account_id)
);

CREATE TABLE IF NOT EXISTS groups_members(
    id INT AUTO_INCREMENT PRIMARY KEY,
    group_id INT NOT NULL,
    account_id INT,
    create_date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX (account_id),
    FOREIGN KEY (group_id) REFERENCES `groups` (id) ON DELETE CASCADE,
    FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS comments(
    id INT AUTO_INCREMENT PRIMARY KEY,
    group_id INT NOT NULL,
    comment VARCHAR(50) NOT NULL,
    account_id INT,
    create_date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX (account_id),
    FOREIGN KEY (group_id) REFERENCES `groups`(id) ON DELETE CASCADE,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS albums(
    id INT AUTO_INCREMENT PRIMARY KEY,
    group_id INT NOT NULL,
    album_name VARCHAR(20) NOT NULL,
    create_date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (group_id) REFERENCES `groups`(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS photos(
    id INT AUTO_INCREMENT PRIMARY KEY,
    album_id INT NOT NULL,
    photo VARCHAR(255) NOT NULL,
    account_id INT,
    create_date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX (account_id),
    FOREIGN KEY (album_id) REFERENCES albums(id) ON DELETE CASCADE,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE SET NULL
);